// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwrhdABECzEWpcNDRwdTnJX2uXAQIG-zw',
    appId: '1:566750681743:web:12ae4ef378bd5d1d206efa',
    messagingSenderId: '566750681743',
    projectId: 'guessit-task',
    authDomain: 'guessit-task.firebaseapp.com',
    storageBucket: 'guessit-task.firebasestorage.app',
    measurementId: 'G-T9TV77HNBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf8AGLeINCC6QuiFbGdUMa_xkLQSA95aM',
    appId: '1:566750681743:android:333df639171abf5b206efa',
    messagingSenderId: '566750681743',
    projectId: 'guessit-task',
    storageBucket: 'guessit-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuF-Wm8tnVpReT3vAVNmNr4DZArfPgFAU',
    appId: '1:566750681743:ios:3eb61923631928ca206efa',
    messagingSenderId: '566750681743',
    projectId: 'guessit-task',
    storageBucket: 'guessit-task.firebasestorage.app',
    iosBundleId: 'com.example.guessitTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuF-Wm8tnVpReT3vAVNmNr4DZArfPgFAU',
    appId: '1:566750681743:ios:3eb61923631928ca206efa',
    messagingSenderId: '566750681743',
    projectId: 'guessit-task',
    storageBucket: 'guessit-task.firebasestorage.app',
    iosBundleId: 'com.example.guessitTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwrhdABECzEWpcNDRwdTnJX2uXAQIG-zw',
    appId: '1:566750681743:web:00da0979b8379ce5206efa',
    messagingSenderId: '566750681743',
    projectId: 'guessit-task',
    authDomain: 'guessit-task.firebaseapp.com',
    storageBucket: 'guessit-task.firebasestorage.app',
    measurementId: 'G-TY41TD5FSR',
  );
}
